//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopCvFake.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NopCV
    {
        public int MaNop { get; set; }
        public Nullable<int> MaDoiTac { get; set; }
        public Nullable<int> MaUser { get; set; }
        public Nullable<int> MaBaiDang { get; set; }
        public Nullable<int> MaProfile { get; set; }
        public string ThuGioiThieu { get; set; }
    
        public virtual CV CV { get; set; }
        public virtual DoiTac DoiTac { get; set; }
        public virtual User User { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
