//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopCvFake.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.NopCVs = new HashSet<NopCV>();
        }
    
        public int MaProfile { get; set; }
        public string ChucVuUngTuyen { get; set; }
        public string HinhCV { get; set; }
        public string KinhNghiem { get; set; }
        public string HocVan { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<int> MaUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NopCV> NopCVs { get; set; }
        public virtual User User { get; set; }
    }
}
